### ISSUE TITLE
Confusing failure if actions/checkout isn't used

### ISSUE THREAD

**Issue by dechamps** [WolleTD/clang-format-checker#15]
I tried to use `clang-format-checker` using the following bare-bones config:

```yaml
on: [push, pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: wolletd/clang-format-checker@v1
        with:
          target-ref: master
```

This [failed](https://github.com/dechamps/FlexASIO/actions/runs/4461009108/jobs/7834533016) in a somewhat confusing way: it aborts after `Initializing repository...` without any error message.

I eventually figured out that adding `- uses: actions/checkout@v3` before the `clang-format-checker` fixes the problem. Looking at the code it's not clear to me if this working as intended? If it is, then it would be great to mention the need to checkout first in the example config in the README.
